//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlsChecker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrlsChecker.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root ver=&quot;1.0&quot;&gt;
        ///  &lt;status value=&quot;ok&quot; defMsg=&quot;Service not available&quot;&gt;
        ///    &lt;msg culture=&quot;it-IT&quot; text=&quot;servizio sospeso&quot; targetVer=&quot;1.0.6&quot; op=&quot;eq&quot;/&gt;
        ///  &lt;/status&gt;
        ///  &lt;item&gt;
        ///    &lt;url&gt;http://www.youtube.com/watch?v=0tlrwsu1IQM&lt;/url&gt;
        ///    &lt;desc&gt;
        ///      &lt;descItem lang=&quot;it-IT&quot; value=&quot;Il piccolo Alex&quot;/&gt;
        ///    &lt;/desc&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;url&gt;http://www.youtube.com/watch?v=Lt5q6Gx_DsI&lt;/url&gt;
        ///    &lt;desc&gt;
        ///      &lt;descItem lang=&quot;it-IT&quot; value=&quot;L&apos;esame della vista&quot;/&gt;
        ///    &lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string peppa {
            get {
                return ResourceManager.GetString("peppa", resourceCulture);
            }
        }
    }
}
